[package]
name = "phantom-of-scopa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.0"
bevy_renet = "0.0.10"
rand = "0.8.5"
renet = "0.0.14"
scopa-lib = { path = "../scopa-lib/" }
